class product {
    constructor(id, maker, name, productImg, price, description, quantity) {
        this.id = id;
        this.maker = maker;
        this.name = name;
        this.productImg = productImg;
        this.price = price;
        this.description = description;
        this.quantity = quantity;
    }
}

let iPhoneSE = new product(0, 'Apple', 'iPhone SE 128GB', './resources/imgStock/iPhoneSE.jpg', 289999, 'El diseño de este iPhone es casi idéntico al iPhone 8 (un botón físico, con marcos arriba y abajo con el Touch ID de la pantalla a excepción de detalles como la posición del logotipo más centrado y sin la pablara iPhone pero utiliza el mismo sistema en chip A13 Bionic que la línea del iPhone 11 con una menor batería comparado al 11). Los pedidos anticipados comenzaron el 17 de abril y las entregas comenzaron el 24 de abril de 2020.', 1);
let A50 = new product(1, 'Noblex', 'A50', './resources/imgStock/A50.jpg', 30999, 'El celular Noblex A50 posee un moderno y atractivo diseño en color negro que querrás tener en tus manos. Está pensado para que puedas conectarte con amigos, realizar transmisiones en vivo, y disfrutar de todas tus series y películas favoritas en una calidad excelente sin perderte de nada.', 1);
let A5H = new product(2, 'Alcatel', '5H 128GB', './resources/imgStock/5H.jpg', 50879, 'Lleva tus fotos a otro nivel con la cámara con IA de 48 MP, la cámara macro de 2 MP y la cámara super gran angular de 5 MP del Alcatel 5H. Puedes pasar horas haciendo fotos gracias al procesador supereficiente de ocho núcleos y a la batería de 4000 mAh del Alcatel 5H. Disfruta de imágenes y vídeos envolventes con la pantalla panoramica HD+ de 6,52 pulgadas y su relación de aspecto de 20:9. Podés hacer mucho más gracias al botón del Asistente de Google, que proporciona comodidad y ayuda al instante. Su diseño se destaca en cualquier lugar gracias al acabado degradado y el cristal 2.5D de tacto suave.', 1);
let A3H = new product(3, 'Alcatel', '3H Plus 64GB', './resources/imgStock/3H.jpg', 46079, 'Transforma tus imágenes con la triple cámara con IA del Alcatel 3H y guarda un recuerdo de tus momentos más importantes. Sus cámaras con IA de 13 MP, super gran angular de 2 MP y de profundidad de 2 MP, te permiten capturar cualquier situación, ya sea con iluminación tenue o intensa. Disfruta más de la vida gracias al procesador Octa-Core ultrarrápido, que gestiona mejor juegos, streamings, capturas y muchas más acciones. ¡Y una batería de 4000 mAh que dura todo el día! Completa tus tareas diarias sin esfuerzo con el botón del Asistente de Google. Descubre una gran pantalla HD+ ampliada de 6,22 pulgadas, que brilla con sus detalles radiales ranurados que atrapan la luz', 1);
let T30SE = new product(4, 'TCL', '30 SE 128GB', './resources/imgStock/30SE.jpg', 42749, 'Transforma tus imágenes con la triple cámara con IA de este celular y guarda un recuerdo de tus momentos más importantes. Sus cámaras con IA de 13 MP, super gran angular de 2 MP y de profundidad de 2 MP, te permiten capturar cualquier situación, ya sea con iluminación tenue o intensa. Disfruta más de la vida gracias al procesador Octa-Core ultrarrápido, que gestiona mejor juegos, streamings, capturas y muchas más acciones. ¡Y una batería de 4000 mAh que dura todo el día! Completa tus tareas diarias sin esfuerzo con el botón del Asistente de Google. Descubre una gran pantalla HD+ ampliada de 6,22 pulgadas, que brilla con sus detalles radiales ranurados que atrapan la luz', 1);
let T30E = new product(5, 'TCL', '30E 64GB', './resources/imgStock/30E.jpg', 51999, 'Transforma tus imágenes con la triple cámara con IA de este celular y guarda un recuerdo de tus momentos más importantes. Sus cámaras con IA de 13 MP, super gran angular de 2 MP y de profundidad de 2 MP, te permiten capturar cualquier situación, ya sea con iluminación tenue o intensa. Disfruta más de la vida gracias al procesador Octa-Core ultrarrápido, que gestiona mejor juegos, streamings, capturas y muchas más acciones. ¡Y una batería de 4000 mAh que dura todo el día! Completa tus tareas diarias sin esfuerzo con el botón del Asistente de Google. Descubre una gran pantalla HD+ ampliada de 6,22 pulgadas, que brilla con sus detalles radiales ranurados que atrapan la luz', 1);
let T20B = new product(6, 'TCL', '20B 64GB', './resources/imgStock/20B.jpg', 45499, 'Transforma tus imágenes con la triple cámara con IA de este celular y guarda un recuerdo de tus momentos más importantes. Sus cámaras con IA de 13 MP, super gran angular de 2 MP y de profundidad de 2 MP, te permiten capturar cualquier situación, ya sea con iluminación tenue o intensa. Disfruta más de la vida gracias al procesador Octa-Core ultrarrápido, que gestiona mejor juegos, streamings, capturas y muchas más acciones. ¡Y una batería de 4000 mAh que dura todo el día! Completa tus tareas diarias sin esfuerzo con el botón del Asistente de Google. Descubre una gran pantalla HD+ ampliada de 6,22 pulgadas, que brilla con sus detalles radiales ranurados que atrapan la luz', 1);
let T20E = new product(7, 'TCL', '20E 128GB', './resources/imgStock/20E.jpg', 49389, 'Transforma tus imágenes con la triple cámara con IA de este celular y guarda un recuerdo de tus momentos más importantes. Sus cámaras con IA de 13 MP, super gran angular de 2 MP y de profundidad de 2 MP, te permiten capturar cualquier situación, ya sea con iluminación tenue o intensa. Disfruta más de la vida gracias al procesador Octa-Core ultrarrápido, que gestiona mejor juegos, streamings, capturas y muchas más acciones. ¡Y una batería de 4000 mAh que dura todo el día! Completa tus tareas diarias sin esfuerzo con el botón del Asistente de Google. Descubre una gran pantalla HD+ ampliada de 6,22 pulgadas, que brilla con sus detalles radiales ranurados que atrapan la luz', 1);
let L7 = new product(8, 'TCL', 'L7 32GB', './resources/imgStock/L7.jpg', 29179, 'Transforma tus imágenes con la triple cámara con IA de este celular y guarda un recuerdo de tus momentos más importantes. Sus cámaras con IA de 13 MP, super gran angular de 2 MP y de profundidad de 2 MP, te permiten capturar cualquier situación, ya sea con iluminación tenue o intensa. Disfruta más de la vida gracias al procesador Octa-Core ultrarrápido, que gestiona mejor juegos, streamings, capturas y muchas más acciones. ¡Y una batería de 4000 mAh que dura todo el día! Completa tus tareas diarias sin esfuerzo con el botón del Asistente de Google. Descubre una gran pantalla HD+ ampliada de 6,22 pulgadas, que brilla con sus detalles radiales ranurados que atrapan la luz', 1);
let M30PRO = new product(9, 'Motorola', 'EDGE 30PRO 256GB', './resources/imgStock/30PRO.jpg', 216209, 'Transforma tus imágenes con la triple cámara con IA de este celular y guarda un recuerdo de tus momentos más importantes. Sus cámaras con IA de 13 MP, super gran angular de 2 MP y de profundidad de 2 MP, te permiten capturar cualquier situación, ya sea con iluminación tenue o intensa. Disfruta más de la vida gracias al procesador Octa-Core ultrarrápido, que gestiona mejor juegos, streamings, capturas y muchas más acciones. ¡Y una batería de 4000 mAh que dura todo el día! Completa tus tareas diarias sin esfuerzo con el botón del Asistente de Google. Descubre una gran pantalla HD+ ampliada de 6,22 pulgadas, que brilla con sus detalles radiales ranurados que atrapan la luz', 1);
let G52 = new product(10, 'Motorola', 'G52 128GB', './resources/imgStock/G52.jpg', 69999, 'Transforma tus imágenes con la triple cámara con IA de este celular y guarda un recuerdo de tus momentos más importantes. Sus cámaras con IA de 13 MP, super gran angular de 2 MP y de profundidad de 2 MP, te permiten capturar cualquier situación, ya sea con iluminación tenue o intensa. Disfruta más de la vida gracias al procesador Octa-Core ultrarrápido, que gestiona mejor juegos, streamings, capturas y muchas más acciones. ¡Y una batería de 4000 mAh que dura todo el día! Completa tus tareas diarias sin esfuerzo con el botón del Asistente de Google. Descubre una gran pantalla HD+ ampliada de 6,22 pulgadas, que brilla con sus detalles radiales ranurados que atrapan la luz', 1);
let G41 = new product(11, 'Motorola', 'G41 128GB', './resources/imgStock/G41.jpg', 61999, 'Transforma tus imágenes con la triple cámara con IA de este celular y guarda un recuerdo de tus momentos más importantes. Sus cámaras con IA de 13 MP, super gran angular de 2 MP y de profundidad de 2 MP, te permiten capturar cualquier situación, ya sea con iluminación tenue o intensa. Disfruta más de la vida gracias al procesador Octa-Core ultrarrápido, que gestiona mejor juegos, streamings, capturas y muchas más acciones. ¡Y una batería de 4000 mAh que dura todo el día! Completa tus tareas diarias sin esfuerzo con el botón del Asistente de Google. Descubre una gran pantalla HD+ ampliada de 6,22 pulgadas, que brilla con sus detalles radiales ranurados que atrapan la luz', 1);
let M30Fusion = new product(12, 'Motorola', 'EDGE 30 Fusión 256GB', './resources/imgStock/30Fusion.jpg', 198699, 'Transforma tus imágenes con la triple cámara con IA de este celular y guarda un recuerdo de tus momentos más importantes. Sus cámaras con IA de 13 MP, super gran angular de 2 MP y de profundidad de 2 MP, te permiten capturar cualquier situación, ya sea con iluminación tenue o intensa. Disfruta más de la vida gracias al procesador Octa-Core ultrarrápido, que gestiona mejor juegos, streamings, capturas y muchas más acciones. ¡Y una batería de 4000 mAh que dura todo el día! Completa tus tareas diarias sin esfuerzo con el botón del Asistente de Google. Descubre una gran pantalla HD+ ampliada de 6,22 pulgadas, que brilla con sus detalles radiales ranurados que atrapan la luz', 1);
let G82 = new product(13, 'Motorola', 'G82 128GB', './resources/imgStock/G82.jpg', 89999, 'Lleva tus fotos a otro nivel con la cámara con IA de 48 MP, la cámara macro de 2 MP y la cámara super gran angular de 5 MP de este celular. Puedes pasar horas haciendo fotos gracias al procesador supereficiente de ocho núcleos y a la batería de 4000 mAh de este celular. Disfruta de imágenes y vídeos envolventes con la pantalla panoramica HD+ de 6,52 pulgadas y su relación de aspecto de 20:9. Podés hacer mucho más gracias al botón del Asistente de Google, que proporciona comodidad y ayuda al instante. Su diseño se destaca en cualquier lugar gracias al acabado degradado y el cristal 2.5D de tacto suave.', 1);
let G42 = new product(14, 'Motorola', 'G42 128GB', './resources/imgStock/G42.jpg', 69599, 'Lleva tus fotos a otro nivel con la cámara con IA de 48 MP, la cámara macro de 2 MP y la cámara super gran angular de 5 MP de este celular. Puedes pasar horas haciendo fotos gracias al procesador supereficiente de ocho núcleos y a la batería de 4000 mAh de este celular. Disfruta de imágenes y vídeos envolventes con la pantalla panoramica HD+ de 6,52 pulgadas y su relación de aspecto de 20:9. Podés hacer mucho más gracias al botón del Asistente de Google, que proporciona comodidad y ayuda al instante. Su diseño se destaca en cualquier lugar gracias al acabado degradado y el cristal 2.5D de tacto suave.', 1);
let M30 = new product(15, 'Motorola', 'EDGE 30 128GB', './resources/imgStock/30.jpg', 119999, 'Lleva tus fotos a otro nivel con la cámara con IA de 48 MP, la cámara macro de 2 MP y la cámara super gran angular de 5 MP de este celular. Puedes pasar horas haciendo fotos gracias al procesador supereficiente de ocho núcleos y a la batería de 4000 mAh de este celular. Disfruta de imágenes y vídeos envolventes con la pantalla panoramica HD+ de 6,52 pulgadas y su relación de aspecto de 20:9. Podés hacer mucho más gracias al botón del Asistente de Google, que proporciona comodidad y ayuda al instante. Su diseño se destaca en cualquier lugar gracias al acabado degradado y el cristal 2.5D de tacto suave.', 1);
let E20 = new product(16, 'Motorola', 'E20  32GB', './resources/imgStock/E20.jpg', 37599, 'Lleva tus fotos a otro nivel con la cámara con IA de 48 MP, la cámara macro de 2 MP y la cámara super gran angular de 5 MP de este celular. Puedes pasar horas haciendo fotos gracias al procesador supereficiente de ocho núcleos y a la batería de 4000 mAh de este celular. Disfruta de imágenes y vídeos envolventes con la pantalla panoramica HD+ de 6,52 pulgadas y su relación de aspecto de 20:9. Podés hacer mucho más gracias al botón del Asistente de Google, que proporciona comodidad y ayuda al instante. Su diseño se destaca en cualquier lugar gracias al acabado degradado y el cristal 2.5D de tacto suave.', 1);
let E40 = new product(17, 'Motorola', 'E40 64GB', './resources/imgStock/E40.jpg', 47999, 'Lleva tus fotos a otro nivel con la cámara con IA de 48 MP, la cámara macro de 2 MP y la cámara super gran angular de 5 MP de este celular. Puedes pasar horas haciendo fotos gracias al procesador supereficiente de ocho núcleos y a la batería de 4000 mAh de este celular. Disfruta de imágenes y vídeos envolventes con la pantalla panoramica HD+ de 6,52 pulgadas y su relación de aspecto de 20:9. Podés hacer mucho más gracias al botón del Asistente de Google, que proporciona comodidad y ayuda al instante. Su diseño se destaca en cualquier lugar gracias al acabado degradado y el cristal 2.5D de tacto suave.', 1);
// let = new product(18, 'Samsung', '', './resources/imgStock/.jpg', , 'Transforma tus imágenes con la triple cámara con IA de este celular y guarda un recuerdo de tus momentos más importantes. Sus cámaras con IA de 13 MP, super gran angular de 2 MP y de profundidad de 2 MP, te permiten capturar cualquier situación, ya sea con iluminación tenue o intensa. Disfruta más de la vida gracias al procesador Octa-Core ultrarrápido, que gestiona mejor juegos, streamings, capturas y muchas más acciones. ¡Y una batería de 4000 mAh que dura todo el día! Completa tus tareas diarias sin esfuerzo con el botón del Asistente de Google. Descubre una gran pantalla HD+ ampliada de 6,22 pulgadas, que brilla con sus detalles radiales ranurados que atrapan la luz', 1);
// let = new product(19, 'Samsung', '', './resources/imgStock/.jpg', , 'Transforma tus imágenes con la triple cámara con IA de este celular y guarda un recuerdo de tus momentos más importantes. Sus cámaras con IA de 13 MP, super gran angular de 2 MP y de profundidad de 2 MP, te permiten capturar cualquier situación, ya sea con iluminación tenue o intensa. Disfruta más de la vida gracias al procesador Octa-Core ultrarrápido, que gestiona mejor juegos, streamings, capturas y muchas más acciones. ¡Y una batería de 4000 mAh que dura todo el día! Completa tus tareas diarias sin esfuerzo con el botón del Asistente de Google. Descubre una gran pantalla HD+ ampliada de 6,22 pulgadas, que brilla con sus detalles radiales ranurados que atrapan la luz', 1);
// let = new product(20, 'Samsung', '', './resources/imgStock/.jpg', , 'Transforma tus imágenes con la triple cámara con IA de este celular y guarda un recuerdo de tus momentos más importantes. Sus cámaras con IA de 13 MP, super gran angular de 2 MP y de profundidad de 2 MP, te permiten capturar cualquier situación, ya sea con iluminación tenue o intensa. Disfruta más de la vida gracias al procesador Octa-Core ultrarrápido, que gestiona mejor juegos, streamings, capturas y muchas más acciones. ¡Y una batería de 4000 mAh que dura todo el día! Completa tus tareas diarias sin esfuerzo con el botón del Asistente de Google. Descubre una gran pantalla HD+ ampliada de 6,22 pulgadas, que brilla con sus detalles radiales ranurados que atrapan la luz', 1);
// let = new product(21, 'Samsung', '', './resources/imgStock/.jpg', , 'Transforma tus imágenes con la triple cámara con IA de este celular y guarda un recuerdo de tus momentos más importantes. Sus cámaras con IA de 13 MP, super gran angular de 2 MP y de profundidad de 2 MP, te permiten capturar cualquier situación, ya sea con iluminación tenue o intensa. Disfruta más de la vida gracias al procesador Octa-Core ultrarrápido, que gestiona mejor juegos, streamings, capturas y muchas más acciones. ¡Y una batería de 4000 mAh que dura todo el día! Completa tus tareas diarias sin esfuerzo con el botón del Asistente de Google. Descubre una gran pantalla HD+ ampliada de 6,22 pulgadas, que brilla con sus detalles radiales ranurados que atrapan la luz', 1);
// let = new product(22, 'Samsung', '', './resources/imgStock/.jpg', , 'Transforma tus imágenes con la triple cámara con IA de este celular y guarda un recuerdo de tus momentos más importantes. Sus cámaras con IA de 13 MP, super gran angular de 2 MP y de profundidad de 2 MP, te permiten capturar cualquier situación, ya sea con iluminación tenue o intensa. Disfruta más de la vida gracias al procesador Octa-Core ultrarrápido, que gestiona mejor juegos, streamings, capturas y muchas más acciones. ¡Y una batería de 4000 mAh que dura todo el día! Completa tus tareas diarias sin esfuerzo con el botón del Asistente de Google. Descubre una gran pantalla HD+ ampliada de 6,22 pulgadas, que brilla con sus detalles radiales ranurados que atrapan la luz', 1);
// let = new product(23, 'Samsung', '', './resources/imgStock/.jpg', , 'Transforma tus imágenes con la triple cámara con IA de este celular y guarda un recuerdo de tus momentos más importantes. Sus cámaras con IA de 13 MP, super gran angular de 2 MP y de profundidad de 2 MP, te permiten capturar cualquier situación, ya sea con iluminación tenue o intensa. Disfruta más de la vida gracias al procesador Octa-Core ultrarrápido, que gestiona mejor juegos, streamings, capturas y muchas más acciones. ¡Y una batería de 4000 mAh que dura todo el día! Completa tus tareas diarias sin esfuerzo con el botón del Asistente de Google. Descubre una gran pantalla HD+ ampliada de 6,22 pulgadas, que brilla con sus detalles radiales ranurados que atrapan la luz', 1);
// let = new product(24, 'Samsung', '', './resources/imgStock/.jpg', , 'Transforma tus imágenes con la triple cámara con IA de este celular y guarda un recuerdo de tus momentos más importantes. Sus cámaras con IA de 13 MP, super gran angular de 2 MP y de profundidad de 2 MP, te permiten capturar cualquier situación, ya sea con iluminación tenue o intensa. Disfruta más de la vida gracias al procesador Octa-Core ultrarrápido, que gestiona mejor juegos, streamings, capturas y muchas más acciones. ¡Y una batería de 4000 mAh que dura todo el día! Completa tus tareas diarias sin esfuerzo con el botón del Asistente de Google. Descubre una gran pantalla HD+ ampliada de 6,22 pulgadas, que brilla con sus detalles radiales ranurados que atrapan la luz', 1);
// let = new product(25, 'Samsung', '', './resources/imgStock/.jpg', , 'Transforma tus imágenes con la triple cámara con IA de este celular y guarda un recuerdo de tus momentos más importantes. Sus cámaras con IA de 13 MP, super gran angular de 2 MP y de profundidad de 2 MP, te permiten capturar cualquier situación, ya sea con iluminación tenue o intensa. Disfruta más de la vida gracias al procesador Octa-Core ultrarrápido, que gestiona mejor juegos, streamings, capturas y muchas más acciones. ¡Y una batería de 4000 mAh que dura todo el día! Completa tus tareas diarias sin esfuerzo con el botón del Asistente de Google. Descubre una gran pantalla HD+ ampliada de 6,22 pulgadas, que brilla con sus detalles radiales ranurados que atrapan la luz', 1);
// let = new product(26, 'Samsung', '', './resources/imgStock/.jpg', , 'Lleva tus fotos a otro nivel con la cámara con IA de 48 MP, la cámara macro de 2 MP y la cámara super gran angular de 5 MP de este celular. Puedes pasar horas haciendo fotos gracias al procesador supereficiente de ocho núcleos y a la batería de 4000 mAh de este celular. Disfruta de imágenes y vídeos envolventes con la pantalla panoramica HD+ de 6,52 pulgadas y su relación de aspecto de 20:9. Podés hacer mucho más gracias al botón del Asistente de Google, que proporciona comodidad y ayuda al instante. Su diseño se destaca en cualquier lugar gracias al acabado degradado y el cristal 2.5D de tacto suave.', 1);
// let = new product(27, 'Samsung', '', './resources/imgStock/.jpg', , 'Lleva tus fotos a otro nivel con la cámara con IA de 48 MP, la cámara macro de 2 MP y la cámara super gran angular de 5 MP de este celular. Puedes pasar horas haciendo fotos gracias al procesador supereficiente de ocho núcleos y a la batería de 4000 mAh de este celular. Disfruta de imágenes y vídeos envolventes con la pantalla panoramica HD+ de 6,52 pulgadas y su relación de aspecto de 20:9. Podés hacer mucho más gracias al botón del Asistente de Google, que proporciona comodidad y ayuda al instante. Su diseño se destaca en cualquier lugar gracias al acabado degradado y el cristal 2.5D de tacto suave.', 1);

const arrayProducts = [iPhoneSE, A50, A5H, A3H, T30SE, T30E, T20B,
    T20E, L7, M30PRO, G52, G41, M30Fusion, G82, G42, M30, E20, E40
];